<ul class="book-list clearfix">
  <li class="active">
    <div class="img-box">
      <img src="/static/img/fm.jpg" alt="世界疯狂世界疯狂世界疯狂世界疯狂" />
    </div>
    <h4><a href="#" target="_blank">世界疯狂世界疯狂世界疯狂世界疯狂</a></h4>
    <p>
      <em>￥42.80</em>
      <strong>￥31.20</strong>
    </p>
  </li>
  <li>
    <div class="img-box">
      <img src="/static/img/fm.jpg" alt="世界疯狂世界疯狂世界疯狂世界疯狂" />
    </div>
    <h4><a href="#" target="_blank">世界疯狂世界疯狂世界疯狂世界疯狂</a></h4>
    <p>
      <em>￥42.80</em>
      <strong>￥31.20</strong>
    </p>
  </li>
  <li>
    <div class="img-box">
      <img src="/static/img/fm.jpg" alt="世界疯狂世界疯狂世界疯狂世界疯狂" />
    </div>
    <h4><a href="#" target="_blank">世界疯狂世界疯狂世界疯狂世界疯狂</a></h4>
    <p>
      <em>￥42.80</em>
      <strong>￥31.20</strong>
    </p>
  </li>
  <li>
    <div class="img-box">
      <img src="/static/img/fm.jpg" alt="世界疯狂世界疯狂世界疯狂世界疯狂" />
    </div>
    <h4><a href="#" target="_blank">世界疯狂世界疯狂世界疯狂世界疯狂</a></h4>
    <p>
      <em>￥42.80</em>
      <strong>￥31.20</strong>
    </p>
  </li>
  <li>
    <div class="img-box">
      <img src="/static/img/fm.jpg" alt="世界疯狂世界疯狂世界疯狂世界疯狂" />
    </div>
    <h4><a href="#" target="_blank">世界疯狂世界疯狂世界疯狂世界疯狂</a></h4>
    <p>
      <em>￥42.80</em>
      <strong>￥31.20</strong>
    </p>
  </li>
  <li>
    <div class="img-box">
      <img src="/static/img/fm.jpg" alt="世界疯狂世界疯狂世界疯狂世界疯狂" />
    </div>
    <h4><a href="#" target="_blank">世界疯狂世界疯狂世界疯狂世界疯狂</a></h4>
    <p>
      <em>￥42.80</em>
      <strong>￥31.20</strong>
    </p>
  </li>
</ul>
