<div class="slider">
  <ul class="slider-list">
    <li class="slider-item"><a href="#" target="_blank"><img src="/static/img/banner/banner_01.jpg" alt="" /></a></li>
    <li class="slider-item"><a href="#" target="_blank"><img src="/static/img/banner/banner_01.jpg" alt="" /></a></li>
    <li class="slider-item"><a href="#" target="_blank"><img src="/static/img/banner/banner_01.jpg" alt="" /></a></li>
    <li class="slider-item"><a href="#" target="_blank"><img src="/static/img/banner/banner_01.jpg" alt="" /></a></li>
    <li class="slider-item"><a href="#" target="_blank"><img src="/static/img/banner/banner_01.jpg" alt="" /></a></li>
  </ul>
</div>