<div class="backtop"></div>
<div id="footer">
  <div class="container">
    <div class="footer-pic">
    </div>
    <div class="footer-public clearfix">
      <div class="item">
        <h4>售后服务</h4>
        <a href="http://book.zxhsd.com/help/thyz.shtml" target="_blank">退换货原则</a><br>
        <a href="http://book.zxhsd.com/help/fpzd.shtml" target="_blank">退款及发票</a>
      </div>
      <div class="item">
        <h4>我的订单</h4>
        <a href="http://book.zxhsd.com/help/ddzt.shtml" target="_blank">订单状态</a><br>
        <a href="http://book.zxhsd.com/help/ddfy.shtml" target="_blank">订单费用</a><br>
        <a href="http://book.zxhsd.com/help/ddxg.shtml" target="_blank">订单修改与取消</a>
      </div>
      <div class="item">
        <h4>订单支付</h4>
        <a href="http://book.zxhsd.com/help/pay_ol.shtml" target="_blank">在线支付</a><br>
        <a href="http://book.zxhsd.com/help/hdfk.shtml" target="_blank">货到付款</a><br>
        <a href="http://book.zxhsd.com/help/yjhk.shtml" target="_blank">银行汇款</a><br>
        <a href="http://book.zxhsd.com/help/djzd.shtml" target="_blank">定金制度</a>
      </div>
      <div class="item">
        <h4>联系我们</h4>
        <a href="http://book.zxhsd.com/help/yjyjy.shtml" target="_blank">意见与联系</a>
      </div>
    </div>
    <div class="footer-bottom">
      <span><a href="http://book.zxhsd.com/about/lxwm.shtml" target="_blank">联系连锁店</a></span>
      <span>|</span>
      <span><a href="http://www.zxhsd.com/Club/ddrl.jsp" target="_blank">汇款单招领</a></span>
      <span>|</span>
      <span><a href="http://book.zxhsd.com/Flink/" target="_blank">友情链接</a></span>
      <span>|</span>
      <span><a href="http://book.zxhsd.com/help/help.shtml" target="_blank">帮助中心</a></span>
      <span>|</span>
      <span><a href="http://book.zxhsd.com/help/glzd/" target="_blank">管理制度</a></span>
      <p>
        浙江省新华书店集体有限公司主办 ICP证：浙B2-20110302<br>
        2005-2014版权所有&copy;
      </p>
    </div>
  </div>
</div>
