<div id="header">
  <div class="top-bar">
    <div class="container clearfix">
      <div class="left">
        <span>您好！欢迎光临！ </span>
      </div>
      <div class="right">
        <a href="http://www.zxhsd.com/Club/searchOrder.jsp" class="order"><i></i>我的订单</a>
        <span> | </span>
        <a href="http://www.zxhsd.com/Club/ly_cx.jsp" class="msg"><i></i>我的消息</a>
        <span> | </span>
        <a href="http://www.zxhsd.com/Shopping/shopping1.jsp" class="cart"><i></i>购物车</a>
        <span> | </span>
        <a href="http://book.zxhsd.com/help/help.shtml" class="help"><i></i>帮助中心</a>
      </div>
    </div>
  </div>
  <div class="logo-search">
    <div class="container clearfix">
      <div class="left">
        <div class="logo left">
          <a href="#"><img src="/static/img/logo.png" alt="" /></a>
        </div>
        <div class="select-store left">
          <a href="#" id="store">选择门店<i></i></a>
        </div>
      </div>
      <div class="right">
        <div class="search-box">
          <form action="http://www.zxhsd.com/search/book_search.jsp" method="post">
            <input type="hidden" name="category" value="gjz">
            <input type="text" class="input input-search left" name="keyword">
            <button type="submit" class="btn btn-search left">搜 索</button>
            <a href="http://www.zxhsd.com/search/ADsearch.jsp">高级<br>搜索</a>
          </form>
        </div>
        <div class="search-list">
          <span>热搜：</span>
          <a href="http://www.zxhsd.com/search/book_search.jsp?keyword=秘密花园&category=gjz">秘密花园</a>
          <a href="http://www.zxhsd.com/search/book_search.jsp?keyword=巴巴爸爸&category=gjz">巴巴爸爸</a>
          <a href="http://www.zxhsd.com/search/book_search.jsp?keyword=查理九世&category=gjz">查理九世</a>
          <a href="http://www.zxhsd.com/search/book_search.jsp?keyword=花千骨&category=gjz">花千骨</a>
          <a href="http://www.zxhsd.com/search/book_search.jsp?keyword=真爱并非运气被爱是种实力&category=gjz">真爱并非运气被爱是种实力</a>
        </div>
      </div>
    </div>
  </div>
  <div id="nav">
    <div class="container clearfix">
      <div class="main-list left">
        <h3>全部商品分类</h3>
        <div class="list">
          <dl class="item first-item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">中国史</a>
              <a href="#">哲学总论</a>
              <a href="#">心理学</a><br>
              <a href="#">军事理论</a>
              <a href="#">政治理论</a>
              <a href="#">宗教</a>
            </dd>
            <div class="sub-item">
              <a href="">中国史</a>
              <span>|</span>
              <a href="">世界史</a>
              <span>|</span>
              <a href="">史学理论</a>
              <span>|</span>
              <a href="">中国哲学</a>
              <span>|</span>
              <a href="">外国哲学</a>
              <span>|</span>
              <a href="">哲学总论</a>
              <br>
              <a href="">中国军事</a>
              <span>|</span>
              <a href="">各国军事</a>
              <span>|</span>
              <a href="">军事理论</a>
              <span>|</span>
              <a href="">中国法律</a>
              <span>|</span>
              <a href="">外国法律</a>
              <span>|</span>
              <a href="">国际法</a>
              <br>
            </div>
          </dl>
          <dl class="item">
            <dt><a href="#">文学书店</a></dt>
            <dd>
              <a href="#">中国小说</a>
              <a href="#">外国小说</a>
              <a href="#">中国诗词</a><br>
              <a href="#">传记</a>
              <a href="#">文学名著</a>
              <a href="#">纪实文学</a>
            </dd>
            <div class="sub-item">
              <a href="">中国史</a>
              <span>|</span>
              <a href="">世界史</a>
              <span>|</span>
              <a href="">史学理论</a>
              <span>|</span>
              <a href="">中国哲学</a>
              <span>|</span>
              <a href="">外国哲学</a>
              <span>|</span>
              <a href="">哲学总论</a>
              <br>
              <a href="">中国军事</a>
              <span>|</span>
              <a href="">各国军事</a>
              <span>|</span>
              <a href="">军事理论</a>
              <span>|</span>
              <a href="">中国法律</a>
              <span>|</span>
              <a href="">外国法律</a>
              <span>|</span>
              <a href="">国际法</a>
              <br>
            </div>
          </dl>
          <dl class="item">
            <dt><a href="#">经管书店</a></dt>
            <dd>
              <a href="#">财经管理</a>
              <a href="#">工商管理</a>
              <a href="#">行业经济</a><br>
              <a href="#">品牌营销</a>
              <a href="#">商务技能</a>
              <a href="#">市场营销</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">少儿书店</a></dt>
            <dd>
              <a href="#">低幼读物</a>
              <a href="#">儿童文学</a>
              <a href="#">绘本</a><br>
              <a href="#">励志成长</a>
              <a href="#">学前教育</a>
              <a href="#">连环画</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">生活书店</a></dt>
            <dd>
              <a href="#">养生保健</a>
              <a href="#">生活窍门</a>
              <a href="#">烹饪食谱</a><br>
              <a href="#">花鸟宠物</a>
              <a href="#">居室设计</a>
              <a href="#">期刊杂志</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">艺术书店</a></dt>
            <dd>
              <a href="#">摄影</a>
              <a href="#">漫画</a>
              <a href="#">绘画</a>
              <a href="#">音乐</a>
              <a href="#">舞蹈</a><br>
              <a href="#">书法篆刻</a>
              <a href="#">工艺美术</a>
              <a href="#">戏剧影视</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">教育书店</a></dt>
            <dd>
              <a href="#">小学教辅</a>
              <a href="#">初中教辅</a>
              <a href="#">高中教辅</a>
              <a href="#">汉语文化</a>
              <a href="#">英语</a>
              <a href="#">日语</a>
              <a href="#">德语</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">医学书店</a></dt>
            <dd>
              <a href="#">中医学</a>
              <a href="#">内科学</a>
              <a href="#">基础医学</a><br>
              <a href="#">儿科学</a>
              <a href="#">肿瘤学</a>
              <a href="#">临床医学</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">计算机书店</a></dt>
            <dd>
              <a href="#">程序与语言</a>
              <a href="#">操作系统</a>
              <a href="#">多媒体</a>
              <a href="#">信息处理与数据</a>
              <a href="#">应用软件</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">科技书店</a></dt>
            <dd>
              <a href="#">农学</a>
              <a href="#">力学</a>
              <a href="#">化学</a>
              <a href="#">地球科学</a><br>
              <a href="#">航空航天</a>
              <a href="#">建筑科学</a>
              <a href="#">交通运输</a>
            </dd>
          </dl>
          <dl class="item">
            <dt class="on"><a href="#">原版书</a></dt>
          </dl>
          <dl class="item">
            <dt class="on"><a href="#">音像</a></dt>
          </dl>
        </div>
      </div>
      <ul class="main-nav left">
        <li><a href="http://book.zxhsd.com/">首页</a></li>
        <li><a href="http://book.zxhsd.com/music.shtml">影音频道</a></li>
        <li><a href="http://www.zxhsd.com/ttc/index.jsp">名优特产</a></li>
        <li><a href="http://book.zxhsd.com/mztsxsb/">排行榜</a></li>
        <li><a href="http://cg.zxhsd.com/b2b_club/login.jsp">新华分销</a></li>
        <li><a href="http://b2g.zxhsd.com/">单位团购</a></li>
        <li><a href="http://www.zxhsd.com/">集团门户</a></li>
        <li><a href="http://wap.zxhsd.com/search.shtml">卖场售书</a></li>
      </ul>
    </div>
  </div>
</div>
