<div id="header">
  <div class="top-bar">
    <div class="container clearfix">
      <div class="left">
        <span>您好！欢迎光临！ </span>
        <a href="http://www.zxhsd.com/Club/login.jsp">登录</a>
        <span> | </span>
        <a href="http://www.zxhsd.com/Club/register_first.jsp">注册</a>
      </div>
      <div class="right">
        <a href="http://www.zxhsd.com/Club/searchOrder.jsp" class="order"><i></i>我的订单</a>
        <span> | </span>
        <a href="http://www.zxhsd.com/Club/ly_cx.jsp" class="msg"><i></i>我的消息</a>
        <span> | </span>
        <a href="http://www.zxhsd.com/Shopping/shopping1.jsp" class="cart"><i></i>购物车</a>
        <span> | </span>
        <a href="http://book.zxhsd.com/help/help.shtml" class="help"><i></i>帮助中心</a>
      </div>
    </div>
  </div>
  <div class="logo-search">
    <div class="container clearfix">
      <div class="left">
        <div class="logo left">
          <a href="#"><img src="/static/img/logo.png" alt="" /></a>
        </div>
        <div class="select-store left">
          <a href="#">选择门店<i></i></a>
        </div>
      </div>
      <div class="right">
        <div class="search-box">
          <form action="http://www.zxhsd.com/search/book_search.jsp" method="post">
            <input type="hidden" name="category" value="gjz">
            <input type="text" class="input input-search left" name="keyword">
            <button type="submit" class="btn btn-search left">搜 索</button>
            <a href="http://www.zxhsd.com/search/ADsearch.jsp">高级<br>搜索</a>
          </form>
        </div>
        <div class="search-list">
          <a href="#">111</a>
          <a href="#">111</a>
          <a href="#">111</a>
          <a href="#">111</a>
          <a href="#">111</a>
        </div>
      </div>
    </div>
  </div>
  <div id="nav">
    <div class="container clearfix">
      <div class="main-list left">
        <h3>全部商品分类</h3>
        <div class="list">
          <dl class="item first-item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
          <dl class="item">
            <dt><a href="#">社科书店</a></dt>
            <dd>
              <a href="#">历史</a>
              <a href="#">人物传记</a>
              <a href="#">哲学</a>
              <a href="#">宗教</a>
              <a href="#">心理学</a>
              <a href="#">励志</a>
              <a href="#">法律</a>
              <a href="#">政治</a>
            </dd>
          </dl>
        </div>
      </div>
      <ul class="main-nav left">
        <li><a href="http://book.zxhsd.com/">首页</a></li>
        <li><a href="http://book.zxhsd.com/music.shtml">影音频道</a></li>
        <li><a href="http://www.zxhsd.com/ttc/index.jsp">名优特产</a></li>
        <li><a href="http://book.zxhsd.com/mztsxsb/">排行榜</a></li>
        <li><a href="http://cg.zxhsd.com/b2b_club/login.jsp">新华分销</a></li>
        <li><a href="http://b2g.zxhsd.com/">单位团购</a></li>
        <li><a href="http://www.zxhsd.com/">集团门户</a></li>
        <li><a href="http://wap.zxhsd.com/search.shtml">卖场售书</a></li>
      </ul>
    </div>
  </div>
</div>
