<div class="author-top clearfix">
  <div class="left">
    <img src="/static/img/author/sun.png" alt="" />
    <h4>沈石溪</h4>
  </div>
  <p class="right">
    <b>简介</b>
    沈石溪，原名沈一鸣。中国作家协会会员，上海作家协会理事，全国儿童文学委员会委员。20世纪80年代初开始从事文学创作，醉心于大自然文学，已出版500多万字的作品。代表作品有《第七条猎狗》《红奶羊》《狼王梦》《混血豺王》《鸟奴》等。所著动物小说将故事性、趣味性和知识性溶为一体，充满哲理内涵，风格独特，深受青少年读者的喜爱。
  </p>
</div>
<div class="author-mid">
  <ul>
    <li><a href="#" target="_blank">《狼王梦》</a></li>
    <li><a href="#" target="_blank">《鸟奴》</a></li>
    <li><a href="#" target="_blank">《野犬女王》</a></li>
  </ul>
</div>
