<div class="author-top clearfix">
  <a href="http://www.zxhsd.com/search/book_search.jsp?keyword=沈石溪&category=gjz" target="_blank">
    <div class="left">
      <img src="/static/img/author/shenshixi.jpg" alt="沈石溪" />
      <h4>沈石溪</h4>
    </div>
    <p class="right">
      <b>简介</b>
      沈石溪，已出版作品500多万字。他的动物小说将故事性、趣味性和知识性融为一体，充满哲理内涵，风格独特，深受青少年读者的喜爱。代表作有《狼王梦》《第七条猎狗》《中华龙鸟》等。
    </p>
  </a>
</div>
<div class="author-mid">
  <ul>
    <li><a href="http://www.zxhsd.com/search/book_search.jsp?keyword=狼王梦&category=gjz" target="_blank">《狼王梦》</a></li>
    <li><a href="http://www.zxhsd.com/search/book_search.jsp?keyword=鸟奴&category=gjz" target="_blank">《鸟奴》</a></li>
    <li><a href="http://www.zxhsd.com/search/book_search.jsp?keyword=野犬女王&category=gjz" target="_blank">《野犬女王》</a></li>
  </ul>
</div>
